steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/peak-vista-424017-v9/cloud-run-source-deploy/gcp/traefik-reverse-proxy:$COMMIT_SHA', '.']
    id: Build

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/peak-vista-424017-v9/cloud-run-source-deploy/gcp/traefik-reverse-proxy:$COMMIT_SHA']
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy traefik-proxy \
          --image us-central1-docker.pkg.dev/peak-vista-424017-v9/cloud-run-source-deploy/gcp/traefik-reverse-proxy:$COMMIT_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --port 80
    id: Deploy

options:
  logging: CLOUD_LOGGING_ONLY  # Set the logging option to CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/peak-vista-424017-v9/cloud-run-source-deploy/gcp/traefik-reverse-proxy:$COMMIT_SHA'
